# Fund development of Claude Lead System
# Remove or comment out any entries that don't apply

github: []
# ko_fi: your-ko-fi-username
# open_collective: your-project
# custom: ["https://buymeacoffee.com/your-username"]
