export const API_SCHEMA = {
  version: "1.0.0",
  generated: "static",
  routes: [
    // System
    {
      method: "GET",
      path: "/health",
      description: "Server health check",
      auth: "none",
      response: "HealthPayload",
    },
    {
      method: "GET",
      path: "/metrics.json",
      description: "Current metrics snapshot",
      auth: "none",
      response: "MetricsPayload",
    },
    {
      method: "GET",
      path: "/metrics/history",
      description: "Metrics history",
      auth: "none",
      params: { limit: "number?" },
      response: "MetricsHistoryPayload",
    },
    {
      method: "GET",
      path: "/metrics/diff",
      description: "Diff oldest vs newest metrics",
      auth: "none",
      response: "MetricsDiffPayload",
    },
    {
      method: "GET",
      path: "/schema/version",
      description: "Schema and API version info",
      auth: "none",
      response: "SchemaVersionPayload",
    },
    {
      method: "GET",
      path: "/schema/routes",
      description: "API route reference",
      auth: "none",
      response: "ApiSchemaPayload",
    },
    {
      method: "GET",
      path: "/reports/latest",
      description: "Latest diagnostic report",
      auth: "none",
      response: "ReportPayload",
    },
    {
      method: "GET",
      path: "/events",
      description: "SSE event stream",
      auth: "none",
      response: "text/event-stream",
    },
    {
      method: "GET",
      path: "/timeline/replay",
      description: "Replay timeline events",
      auth: "none",
      params: { from: "ISO?", to: "ISO?", type: "string?" },
      response: "TimelinePayload",
    },
    {
      method: "POST",
      path: "/reports/comparison",
      description: "Generate comparison report",
      auth: "bearer",
      body: { optional: ["label", "baseline_file"] },
      response: "ComparisonReportPayload",
    },
    {
      method: "POST",
      path: "/snapshots/diff",
      description: "Diff two snapshot history entries",
      auth: "bearer",
      body: { optional: ["before_ts", "after_ts"] },
      response: "SnapshotDiffPayload",
    },
    {
      method: "POST",
      path: "/diagnostics/export",
      description: "Export diagnostics bundle",
      auth: "bearer",
      body: { optional: ["label"] },
      response: "DiagnosticsExportPayload",
    },
    {
      method: "GET",
      path: "/diagnostics/latest",
      description: "Latest diagnostics bundle",
      auth: "none",
      response: "DiagnosticsLatestPayload",
    },

    // Agents
    {
      method: "GET",
      path: "/agents",
      description: "List agents across scopes",
      auth: "none",
      params: {
        scope: "all|local|project|user?",
        include_invalid: "boolean?",
        include_shadowed: "boolean?",
        project_dir: "string?",
      },
      response: "AgentsListPayload",
    },
    {
      method: "GET",
      path: "/agents/:agent_name",
      description: "Get a single agent summary (no prompt body)",
      auth: "none",
      params: { scope: "all|local|project|user?", project_dir: "string?" },
      response: "AgentPayload",
    },
    {
      method: "GET",
      path: "/agents/:agent_name/full",
      description: "Get full agent content including prompt and frontmatter",
      auth: "bearer",
      params: { scope: "all|local|project|user?", project_dir: "string?" },
      response: "AgentPayload",
    },
    {
      method: "POST",
      path: "/agents",
      description: "Create an agent",
      auth: "bearer",
      body: {
        required: ["agent_name", "description"],
        optional: [
          "scope",
          "model",
          "tools",
          "memory",
          "skills",
          "prompt",
          "project_dir",
          "overwrite",
        ],
      },
      response: "AgentMutationPayload",
    },
    {
      method: "PATCH",
      path: "/agents/:agent_name",
      description: "Update an agent",
      auth: "bearer",
      body: {
        optional: [
          "scope",
          "new_name",
          "description",
          "model",
          "tools",
          "memory",
          "skills",
          "prompt",
          "project_dir",
          "overwrite",
        ],
      },
      response: "AgentMutationPayload",
    },
    {
      method: "DELETE",
      path: "/agents/:agent_name",
      description: "Delete an agent",
      auth: "bearer",
      body: { optional: ["scope", "project_dir", "all_scopes"] },
      response: "AgentMutationPayload",
    },
    {
      method: "POST",
      path: "/agents/sync-manifest",
      description: "Regenerate MANIFEST.md agents table",
      auth: "bearer",
      body: {
        optional: [
          "manifest_path",
          "scope",
          "include_invalid",
          "include_shadowed",
          "project_dir",
        ],
      },
      response: "AgentMutationPayload",
    },

    // Teams
    {
      method: "GET",
      path: "/teams",
      description: "List all teams",
      auth: "none",
      response: "TeamsListPayload",
    },
    {
      method: "GET",
      path: "/teams/:team_name",
      description: "Get team details",
      auth: "none",
      response: "TeamDetailPayload",
    },
    {
      method: "GET",
      path: "/teams/:team_name/interrupts",
      description: "Team interrupt queue",
      auth: "none",
      response: "InterruptsPayload",
    },
    {
      method: "GET",
      path: "/teams/:team_name/approvals",
      description: "Team pending approvals",
      auth: "none",
      response: "ApprovalsPayload",
    },
    {
      method: "GET",
      path: "/teams/:team_name/teammates/:id/mirror",
      description: "Focused teammate tmux mirror fallback",
      auth: "none",
      response: "TeammateMirrorPayload",
    },
    {
      method: "GET",
      path: "/teams/:team_name/rebalance-explain",
      description: "Explain rebalance plan",
      auth: "none",
      params: { limit: "number?" },
      response: "RebalanceExplainPayload",
    },
    {
      method: "GET",
      path: "/teams/:team_name/tasks/:task_id/audit",
      description: "Task audit trail",
      auth: "none",
      response: "TaskAuditPayload",
    },
    {
      method: "PATCH",
      path: "/teams/:team_name/interrupt-priorities",
      description: "Update interrupt priority weights",
      auth: "bearer",
      body: {
        optional: [
          "approval",
          "bridge",
          "stale",
          "conflict",
          "budget",
          "error",
          "warn",
          "default",
        ],
      },
      response: "OkPayload",
    },
    {
      method: "POST",
      path: "/teams/:team_name/rebalance",
      description: "Rebalance team tasks",
      auth: "bearer",
      body: {
        optional: [
          "apply",
          "force_path",
          "limit",
          "dispatch_next",
          "include_in_progress",
        ],
      },
      response: "ActionResultPayload",
    },
    {
      method: "POST",
      path: "/teams/:team_name/rebalance-explain",
      description: "Explain rebalance with options",
      auth: "bearer",
      body: { optional: ["limit", "assignee"] },
      response: "RebalanceExplainPayload",
    },
    {
      method: "POST",
      path: "/teams/:team_name/actions/:action",
      description: "Execute team action",
      auth: "bearer",
      body: {
        optional: [
          "team_name",
          "subject",
          "prompt",
          "priority",
          "role_hint",
          "role",
          "directory",
          "force_path",
          "to",
          "content",
          "message",
          "task_id",
          "feedback",
          "session_id",
          "target_name",
          "from",
          "files",
          "blocked_by",
          "acceptance_criteria",
          "metadata",
          "agent",
        ],
      },
      response: "ActionResultPayload",
    },
    {
      method: "POST",
      path: "/teams/:team_name/tasks/:task_id/reassign",
      description: "Reassign task",
      auth: "bearer",
      body: { optional: ["new_assignee", "reason", "progress_context"] },
      response: "OkPayload",
    },
    {
      method: "POST",
      path: "/teams/:team_name/tasks/:task_id/gate-check",
      description: "Run quality gate check",
      auth: "bearer",
      body: {},
      response: "OkPayload",
    },
    {
      method: "POST",
      path: "/teams/:team_name/batch-triage",
      description: "Batch triage operations",
      auth: "bearer",
      body: { optional: ["op", "confirm", "message", "limit"] },
      response: "ActionResultPayload",
    },
    {
      method: "GET",
      path: "/task-templates",
      description: "List task templates",
      auth: "none",
      response: "TaskTemplatesPayload",
    },
    {
      method: "POST",
      path: "/task-templates",
      description: "Create task template",
      auth: "bearer",
      body: {
        optional: [
          "id",
          "name",
          "subject_template",
          "prompt_template",
          "role_hint",
          "priority",
          "quality_gates",
          "acceptance_criteria",
        ],
      },
      response: "TaskTemplatePayload",
    },

    // Actions
    {
      method: "GET",
      path: "/actions",
      description: "List tracked actions",
      auth: "none",
      response: "ActionsListPayload",
    },
    {
      method: "GET",
      path: "/actions/:action_id",
      description: "Get action details",
      auth: "none",
      response: "ActionDetailPayload",
    },
    {
      method: "POST",
      path: "/actions/:action_id/retry",
      description: "Retry failed action",
      auth: "bearer",
      body: {},
      response: "ActionResultPayload",
    },
    {
      method: "POST",
      path: "/actions/:action_id/fallback",
      description: "Fallback failed action to alt path",
      auth: "bearer",
      body: { optional: ["force_path"] },
      response: "ActionResultPayload",
    },
    {
      method: "POST",
      path: "/dispatch",
      description: "Dispatch task to team",
      auth: "bearer",
      body: {
        required: ["team_name"],
        optional: [
          "subject",
          "prompt",
          "directory",
          "priority",
          "role",
          "files",
          "blocked_by",
          "metadata",
          "force_path",
        ],
      },
      response: "ActionResultPayload",
    },
    {
      method: "POST",
      path: "/route/simulate",
      description: "Simulate action routing",
      auth: "bearer",
      body: { required: ["team_name", "action"], optional: ["payload"] },
      response: "SimulationPayload",
    },

    // Native
    {
      method: "GET",
      path: "/native/status",
      description: "Native adapter status",
      auth: "none",
      response: "NativeStatusPayload",
    },
    {
      method: "GET",
      path: "/native/bridge/status",
      description: "Bridge health status",
      auth: "none",
      response: "BridgeStatusPayload",
    },
    {
      method: "GET",
      path: "/native/bridge/validation",
      description: "Bridge validation report",
      auth: "none",
      response: "BridgeValidationPayload",
    },
    {
      method: "POST",
      path: "/native/probe",
      description: "Probe native capabilities",
      auth: "bearer",
      body: {},
      response: "NativeProbePayload",
    },
    {
      method: "POST",
      path: "/native/bridge/ensure",
      description: "Ensure bridge is running",
      auth: "bearer",
      body: { optional: ["team_name", "directory"] },
      response: "BridgeEnsurePayload",
    },
    {
      method: "POST",
      path: "/native/bridge/validate",
      description: "Validate bridge for team",
      auth: "bearer",
      body: {
        optional: [
          "team_name",
          "directory",
          "timeout_ms",
          "timeoutMs",
          "simulate",
        ],
      },
      response: "BridgeValidatePayload",
    },
    {
      method: "POST",
      path: "/native/actions/:action",
      description: "Execute native action directly",
      auth: "bearer",
      body: {
        optional: [
          "team_name",
          "agent",
          "task",
          "message",
          "metadata",
          "goal",
          "members",
          "force_path_mode",
          "timeout_ms",
          "model",
        ],
      },
      response: "ActionResultPayload",
    },

    // UI
    {
      method: "GET",
      path: "/",
      description: "Dashboard HTML",
      auth: "none",
      response: "text/html",
    },
    {
      method: "GET",
      path: "/ui/bootstrap.json",
      description: "UI bootstrap config (CSRF token)",
      auth: "none",
      response: "BootstrapPayload",
    },
    {
      method: "GET",
      path: "/ui/preferences",
      description: "Get UI preferences",
      auth: "none",
      response: "PreferencesPayload",
    },
    {
      method: "GET",
      path: "/ui/app.js",
      description: "Dashboard JavaScript",
      auth: "none",
      response: "application/javascript",
    },
    {
      method: "PUT",
      path: "/ui/preferences",
      description: "Save UI preferences",
      auth: "bearer",
      body: {},
      response: "OkPayload",
    },
    {
      method: "POST",
      path: "/open-dashboard",
      description: "Open dashboard in browser",
      auth: "bearer",
      body: {},
      response: "OkPayload",
    },

    // Maintenance
    {
      method: "POST",
      path: "/maintenance/run",
      description: "Run maintenance sweep",
      auth: "bearer",
      body: { optional: ["source"] },
      response: "MaintenancePayload",
    },
    {
      method: "POST",
      path: "/maintenance/rotate-api-token",
      description: "Rotate API token",
      auth: "bearer",
      body: {},
      response: "TokenRotatePayload",
    },
    {
      method: "GET",
      path: "/checkpoints",
      description: "List checkpoints",
      auth: "none",
      response: "CheckpointsListPayload",
    },
    {
      method: "POST",
      path: "/checkpoints/create",
      description: "Create checkpoint",
      auth: "bearer",
      body: { optional: ["label"] },
      response: "CheckpointPayload",
    },
    {
      method: "POST",
      path: "/checkpoints/restore",
      description: "Restore from checkpoint",
      auth: "bearer",
      body: { required: ["file"] },
      response: "CheckpointPayload",
    },
    {
      method: "GET",
      path: "/events/consistency",
      description: "Event log consistency check",
      auth: "none",
      response: "ConsistencyPayload",
    },
    {
      method: "POST",
      path: "/events/rebuild-check",
      description: "Rebuild and compare from timeline",
      auth: "bearer",
      body: { optional: ["from_ts"] },
      response: "ConsistencyPayload",
    },
    {
      method: "POST",
      path: "/repair/scan",
      description: "Scan for corrupt files",
      auth: "bearer",
      body: {},
      response: "ScanPayload",
    },
    {
      method: "POST",
      path: "/repair/fix",
      description: "Repair corrupt file",
      auth: "bearer",
      body: { required: ["path"], optional: ["dry_run"] },
      response: "RepairPayload",
    },
    {
      method: "GET",
      path: "/schema/migrations",
      description: "List available migrations",
      auth: "none",
      response: "MigrationsPayload",
    },
    {
      method: "GET",
      path: "/health/locks",
      description: "Lock contention metrics",
      auth: "none",
      response: "LockMetricsPayload",
    },
    {
      method: "GET",
      path: "/health/terminals",
      description: "Terminal health report",
      auth: "none",
      response: "TerminalHealthPayload",
    },
    {
      method: "GET",
      path: "/health/hooks",
      description: "Hook validation report",
      auth: "none",
      response: "HookHealthPayload",
    },
    {
      method: "POST",
      path: "/health/hooks/selftest",
      description: "Run hook self-test",
      auth: "bearer",
      body: {},
      response: "HookSelftestPayload",
    },
    {
      method: "GET",
      path: "/health/security-audit",
      description: "Security audit log",
      auth: "none",
      response: "SecurityAuditPayload",
    },
    {
      method: "GET",
      path: "/health/security-audit/export",
      description: "Security audit export (schema-versioned)",
      auth: "none",
      params: { limit: "number?" },
      response: "SecurityAuditExportPayload",
    },
    {
      method: "GET",
      path: "/health/request-audit",
      description: "Request audit log",
      auth: "none",
      response: "RequestAuditPayload",
    },
    {
      method: "GET",
      path: "/backups",
      description: "List pre-op backups",
      auth: "none",
      params: { operation: "string?" },
      response: "BackupsListPayload",
    },
    {
      method: "POST",
      path: "/backups/restore",
      description: "Restore from backup",
      auth: "bearer",
      body: { required: ["file"] },
      response: "RestorePayload",
    },
  ],
};
